### ISSUE TITLE
Service 'EventsWorker' failed.

### ISSUE THREAD

**Issue by bribroder** [PrefectHQ/prefect-helm#155]
I have a very basic test flow which sets `cache_result_in_memory=False` and fails with python 3.10 and prefect>2.10 but works with prefect==2.9.0. I am testing with a local-only setup so there is no server involved:

```
@task
def say_hello():
    print("hello!")


@flow(cache_result_in_memory=False)
def testflow() -> None:
    logger = get_run_logger()
    logger.info("START FLOW")
    say_hello()
    logger.info("END FLOW")
```
```
$ py -c 'from testflow import testflow; testflow()'

11:14:22.447 | INFO    | prefect.engine - Created flow run 'umber-nyala' for flow 'testflow'
11:14:22.569 | INFO    | Flow run 'umber-nyala' - START FLOW
11:14:22.659 | INFO    | Flow run 'umber-nyala' - Created task run 'say_hello-0' for task 'say_hello'
11:14:22.661 | INFO    | Flow run 'umber-nyala' - Executing 'say_hello-0' immediately...
hello!
11:14:22.920 | INFO    | Task run 'say_hello-0' - Finished in state Completed()
11:14:22.924 | INFO    | Flow run 'umber-nyala' - END FLOW
11:14:24.174 | INFO    | Flow run 'umber-nyala' - Finished in state Completed('All states completed.')
11:14:24.615 | ERROR   | prefect._internal.concurrency.services - Service 'EventsWorker' failed.
Traceback (most recent call last):
  File "/opt/conda/envs/testflow/lib/python3.10/site-packages/prefect/_internal/concurrency/services.py", line 114, in _run
    await self._main_loop()
  File "/opt/conda/envs/testflow/lib/python3.10/site-packages/prefect/_internal/concurrency/services.py", line 127, in _main_loop
    item: T = await self._queue.get()
  File "/opt/conda/envs/testflow/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError
```

If I either downgrade to prefect 2.9 or remove `cache_result_in_memory=False`, it works--everything looks the same except for the EventsWorker service error

**Comment by bribroder** [comment]
Ah yes, sorry about that
